# Pollutants
Pollutant.create name: 'NO2', unit: 'µg/m3', name_html: 'NO<sup>2</sup>', unit_html: 'µg/m<sup>3</sup>', selector: 'NO2(µg/m³)', year_limit_spain: 40.0, year_limit_oms: 20.0, description: '<p>El NO<sup>2</sup> presente en el aire de las ciudades proviene en su mayor parte de la oxidación del monóxido de nitrógeno, NO, cuya fuente principal son las emisiones provocadas por los automóviles, sobre todo los diesel. El NO<sup>2</sup> constituye pues un buen indicador de la contaminación debida al trá co rodado. Por otro lado, el NO<sup>2</sup> interviene en diversas reacciones químicas que tienen lugar en la atmósfera, dando lugar tanto a la producción de ozono tropos- férico como de partículas en suspensión secundarias menores de 2,5 micras (PM2,5), las más dañinas para la salud. De modo que a la hora de considerar los efectos del NO<sup>2</sup> sobre la salud se deben tener en cuenta no sólo los efectos directos que provoca, sino también su condición de marcador de la contaminación debida al tráfico y su condición de precursor de otros contaminantes.</p><p>Los óxidos de nitrógeno son en general muy reactivos y al inhalarse afectan al tracto respiratorio. El NO<sup>2</sup> afecta a los tramos más profundos de los pulmones, inhibiendo algunas funciones de los mismos, como la respuesta inmunológica, produciendo una merma de la resistencia a las infecciones. Los niños y asmáticos son los más afectados por exposición a concentraciones agudas de NO<sup>2</sup>. Asimismo, la exposición crónica a bajas concentraciones de NO<sup>2</sup> se ha asociado con un incremento en las enfermedades respiratorias crónicas, el envejecimiento prematuro del pulmón y con la disminución de su capacidad funcional.</p>'
Pollutant.create name: 'PM10', unit: 'µg/m3', name_html: 'PM<sub>10</sub>', unit_html: 'µg/m<sup>3</sup>', selector: 'PM10(µg/m³)', year_limit_spain: 20.0, year_limit_oms: 20.0, description: '<p>El término “partículas en suspensión” abarca un amplio espectro de sustancias orgánicas o inorgánicas, dispersas en el aire, procedentes de fuentes naturales y arti ciales. La combustión de carburantes fósiles generada por el trá co, en especial los vehículos diesel (una de las principales fuentes de contaminación por partículas en las ciudades), puede producir diversos tipos de partículas: partículas grandes, por la liberación de materiales mal quemados (cenizas volátiles), partículas  nas, formadas por la condensación de materiales vaporizados durante la combustión, y partículas secundarias, mediante reacciones atmosféricas de contaminantes desprendidos como gases. En relación con sus efectos sobre la salud se suelen distinguir: las PM<sub>10</sub> (partículas “torácicas” menores de 10 μm que pueden penetrar hasta las vías respiratorias bajas), las PM<sub>2,5</sub> (partículas “respirables” menores de 2,5 μm, que pueden penetrar hasta las zonas de intercambio de gases del pulmón), y las partículas ultra nas (menores de 100 nm, que pueden llegar al torrente circulatorio).</p><p>En el caso de las PM<sub>2,5</sub>, su tamaño hace que sean 100% respirables, penetrando en el aparato respiratorio y depositándose en los alvéolos pulmonares, incluso pudiendo llegar al torrente sanguíneo. Además, estas partículas de menor tamaño están compuestas por elementos que son más tóxicos (como metales pesados y compuestos orgánicos). Todo ello explica que la evidencia científica esté revelando que estas partículas PM<sub>2,5</sub> tienen efectos más severos sobre la salud que las partículas más grandes, PM<sub>10</sub>.</p><p>Las partículas PM<sub>2,5</sub>, por tanto, se pueden acumular en el sistema respiratorio y están asociadas cada vez con mayor consistencia científica con numerosos efectos negativos sobre la salud, como el aumento de las enfermedades respiratorias y la disminución del funcionamiento pulmonar. Los grupos más sensibles –niños, ancianos y personas con padecimientos respiratorios y cardiacos– corren más riesgo de padecer los efectos negativos de este contaminante.</p><p>Asimismo, su tamaño hace que sean más ligeras y por eso, generalmente, permanecen por más tiempo en el aire. Lo que no sólo prolonga sus efectos, sino que facilita el que sean transportadas por el viento a grandes distancias.</p><p>Hoy día los científicos consideran que las partículas en suspensión son el problema de contaminación ambiental más severo, por sus graves afecciones al tracto respiratorio y al pulmón. Están detrás de numerosas enfermedades respiratorias, problemas cardiovasculares y cánceres de pulmón.</p>'
Pollutant.create name: 'Ozó', unit: 'µg/m3', name_html: 'O<sup>3</sup>', unit_html: 'µg/m<sup>3</sup>', selector: 'O3(µg/m³)', year_limit_spain: 120.0, year_limit_oms: 100.0, description: '<p>El ozono es un potente agente oxidante que se forma median- te una compleja serie de reacciones fotoquímicas en las que participan la radiación solar, el dióxido de nitrógeno (NO<sup>2</sup>), el oxígeno y compuestos orgánicos volátiles. Por lo tanto se trata de un contaminante secundario que se forma a partir de conta- minantes precursores cuando se dan las condiciones meteoro- lógicas adecuadas. Los episodios más agudos de ozono tienen lugar en las tardes de verano. Esta molécula, altamente reactiva, tiende a descomponerse en las zonas en las que existe una alta concentración de monóxido de nitrógeno (NO). Esto explica por qué su presencia en el centro de las grandes ciudades suele ser más baja que en los cinturones metropolitanos y en las áreas rurales circundantes. Por otro lado, el ozono se ve con frecuencia implicado en fenómenos de transporte atmosférico a grandes distancias, por lo que también origina problemas de contamina- ción transfronteriza.</p><p>Los efectos adversos sobre la salud tienen que ver con su potente carácter oxidante. A elevadas concentraciones causa irritación en los ojos, super cies mucosas y pulmones. La respuesta a la exposición al ozono puede variar mucho entre individuos por razones genéticas, edad (afecta más a las personas mayores, cu- yos mecanismos reparativos antioxidantes son menos activos), y por la presencia de afecciones respiratorias como alergias y asma, cuyos síntomas son exacerbados por el ozono. Un importante factor que condiciona los efectos de la exposición al ozono sobre los pulmones es la tasa de ventilación. Al aumentar el ritmo de la respiración aumenta el ozono que entra en los pulmones, por lo que sus efectos nocivos se incrementan con el ejercicio físico, y son por esta razón también mayores en los niños. Diversos estudios relacionan el ozono con inflamaciones de pulmón, síntomas respiratorios, e incrementos en la medicación, morbilidad y mortalidad, así como con los nacimientos prematuros.</p>'

# Locations
Location.create code: '08019051', city: 'Barcelona', name: 'Carrer Lluís Sole i Sabaris'
Location.create code: '08019050', city: 'Barcelona', name: 'Ciutadella'
Location.create code: '08019004', city: 'Barcelona', name: 'Poblenou'
Location.create code: '08019052', city: 'Barcelona', name: 'Port Vell'
Location.create code: '08019044', city: 'Barcelona', name: 'Gràcia - Sant Gervasi'
Location.create code: '08019053', city: 'Barcelona', name: 'IES Goya'
Location.create code: '08019055', city: 'Barcelona', name: 'IES Verdaguer'
Location.create code: '08019043', city: 'Barcelona', name: 'Eixample'
Location.create code: '08019057', city: 'Barcelona', name: 'Palau Reial'
Location.create code: '08019054', city: 'Barcelona', name: 'Parc de la Vall d\'Hebron'
Location.create code: '08019028', city: 'Barcelona', name: 'Plaça Universitat'
Location.create code: '08019042', city: 'Barcelona', name: 'Sants'
Location.create code: '08019056', city: 'Barcelona', name: 'Torre Girona'
Location.create code: '08019045', city: 'Barcelona', name: 'Zona Universitària'
Location.create code: '08019049', city: 'Barcelona', name: 'Escullera del Port'
Location.create code: '08169009', city: 'El Prat de Llobregat', name: 'CEM Sagnier'
Location.create code: '08169008', city: 'El Prat de Llobregat', name: 'Jardins de la pau'
Location.create code: '08169007', city: 'El Prat de Llobregat', name: 'Sant Cosme'
Location.create code: '08015001', city: 'Badalona', name: 'Centre'
Location.create code: '08015023', city: 'Badalona', name: 'Assemblea de Catalunya'
Location.create code: '08015020', city: 'Badalona', name: 'Can Cabanyes'
Location.create code: '08015022', city: 'Badalona', name: 'Guàrdia Urbana'
Location.create code: '08015021', city: 'Badalona', name: 'Mont-roig - Ausiàs March'
Location.create code: '08252002', city: 'Barberà del Vallès', name: 'Ajuntament'
Location.create code: '08252006', city: 'Barberà del Vallès', name: 'Moragues - Montserrat'
Location.create code: '08054001', city: 'Castellbisbal', name: 'CEIP Mare de Déu de Montserrat'
Location.create code: '08054003', city: 'Castellbisbal', name: 'Mirador'
Location.create code: '08073001', city: 'Cornellà de Llobregat', name: 'Allende - Bonveí'
Location.create code: '08077002', city: 'Esplugues de Llobregat', name: 'CEIP Isidre Martí'
Location.create code: '08089003', city: 'Gavà', name: 'Centre'
Location.create code: '08089005', city: 'Gavà', name: 'Parc del Mil·leni'
Location.create code: '08096011', city: 'Granollers', name: 'Joan Vinyoli'
Location.create code: '08096014', city: 'Granollers', name: 'Francesc Macià'
Location.create code: '08101001', city: 'Hospitalet de Llobregat', name: 'Avinguda del Torrent Gornal'
Location.create code: '08114006', city: 'Martorell', name: 'Canyameres - Claret'
Location.create code: '08121009', city: 'Mataró', name: 'El Cros'
Location.create code: '08121014', city: 'Mataró', name: 'Laboratori d\'aigües'
Location.create code: '08121012', city: 'Mataró', name: 'Pablo Iglesias'
Location.create code: '08121013', city: 'Mataró', name: 'Passeig dels Molins'
Location.create code: '08123001', city: 'Molins de Rei', name: 'Ajuntament'
Location.create code: '08124009', city: 'Mollet del Vallès', name: 'Pista d\'atletisme'
Location.create code: '08187012', city: 'Sabadell', name: 'Gran Via'
Location.create code: '08187014', city: 'Sabadell', name: 'IES Escola Industrial'
Location.create code: '08194008', city: 'Sant Adrià de Besòs', name: 'Olímpic'
Location.create code: '08205002', city: 'Sant Cugat del Vallès', name: 'Parc de Sant Francesc'
Location.create code: '08211004', city: 'Sant Feliu de Llobregat', name: 'CEIP Martí i Pol'
Location.create code: '08211003', city: 'Sant Feliu de Llobregat', name: 'Eugeni d\'Ors'
Location.create code: '08221004', city: 'Sant Just Desvern', name: 'CEIP Montseny'
Location.create code: '08245013', city: 'Santa Coloma de Gramenet', name: 'Ajuntament'
Location.create code: '08245012', city: 'Santa Coloma de Gramenet', name: 'Balldovina'
Location.create code: '08270005', city: 'Sitges', name: 'Vallcarca Centre'
Location.create code: '08270004', city: 'Sitges', name: 'Vallcarca Dipòsit aigües'
Location.create code: '08270006', city: 'Sitges', name: 'Vallcarca Oficines'
Location.create code: '43148003', city: 'Tarragona', name: 'Bonavista'
Location.create code: '43148026', city: 'Tarragona', name: 'DARP'
Location.create code: '43148028', city: 'Tarragona', name: 'Parc de la Ciutat'
Location.create code: '43148001', city: 'Tarragona', name: 'Sant Salvador'
Location.create code: '43148022', city: 'Tarragona', name: 'Universitat Laboral'
Location.create code: '43148029', city: 'Tarragona', name: 'Port moll d\'inflamables'
Location.create code: '08279001', city: 'Terrassa', name: 'Mina pública d\'aigües'
Location.create code: '08279011', city: 'Terrassa', name: 'Pare Alegre'
Location.create code: '08282001', city: 'Tiana', name: 'Ajuntament'
Location.create code: '08298009', city: 'Vic', name: 'Centre cívic Santa Anna'
Location.create code: '08298008', city: 'Vic', name: 'Estadi'
Location.create code: '08301004', city: 'Viladecans', name: 'Atrium'
Location.create code: '17079003', city: 'Girona', name: 'Escola de Música'
Location.create code: '17079002', city: 'Girona', name: 'mercat del Lleó'
Location.create code: '17079001', city: 'Girona', name: 'parc de la Devesa'