# Pollutants
Pollutant.create name: 'NO2', description: 'Diòxid de Nitrògen', unit: 'µg/m3', name_html: 'NO<sup>2</sup>', unit_html: 'µg/m<sup>3</sup>', selector: 'contaminant3', year_limit_spain: 40.0, year_limit_oms: 20.0
Pollutant.create name: 'PM10', description: 'Partícules en suspensió menors de 10µm', unit: 'µg/m3', name_html: 'PM10', unit_html: 'µg/m<sup>3</sup>', selector: 'contaminant4', year_limit_spain: 40.0, year_limit_oms: 20.0
# Pollutant.create name: 'PM2.5', description: 'Partícules en suspensió menors de 2.5µm', unit: 'µg/m3', name_html: 'PM2.5', unit_html: 'µg/m<sup>3</sup>', selector: 'contaminant13', year_limit_spain: 40.0, year_limit_oms: 20.0
Pollutant.create name: 'Ozó', description: 'Ozó', unit: 'µg/m3', name_html: 'O<sup>3</sup>', unit_html: 'µg/m<sup>3</sup>', selector: 'contaminant5', year_limit_spain: 120.0, year_limit_oms: 100.0

# Locations
Location.create code: '08019051', city: 'Barcelona', name: 'Carrer Lluís Sole i Sabaris'
Location.create code: '08019050', city: 'Barcelona', name: 'Ciutadella'
Location.create code: '08019004', city: 'Barcelona', name: 'Poblenou'
Location.create code: '08019052', city: 'Barcelona', name: 'Port Vell'
Location.create code: '08019044', city: 'Barcelona', name: 'Gràcia - Sant Gervasi'
Location.create code: '08019053', city: 'Barcelona', name: 'IES Goya'
Location.create code: '08019055', city: 'Barcelona', name: 'IES Verdaguer'
Location.create code: '08019043', city: 'Barcelona', name: 'Eixample'
Location.create code: '08019057', city: 'Barcelona', name: 'Palau Reial'
Location.create code: '08019054', city: 'Barcelona', name: 'Parc de la Vall d\'Hebron'
Location.create code: '08019028', city: 'Barcelona', name: 'Plaça Universitat'
Location.create code: '08019042', city: 'Barcelona', name: 'Sants'
Location.create code: '08019056', city: 'Barcelona', name: 'Torre Girona'
Location.create code: '08019045', city: 'Barcelona', name: 'Zona Universitària'
Location.create code: '08019049', city: 'Barcelona', name: 'Escullera del Port'
Location.create code: '08169009', city: 'El Prat de Llobregat', name: 'CEM Sagnier'
Location.create code: '08169008', city: 'El Prat de Llobregat', name: 'Jardins de la pau'
Location.create code: '08169007', city: 'El Prat de Llobregat', name: 'Sant Cosme'
Location.create code: '08015001', city: 'Badalona', name: 'Centre'
Location.create code: '08015023', city: 'Badalona', name: 'Assemblea de Catalunya'
Location.create code: '08015020', city: 'Badalona', name: 'Can Cabanyes'
Location.create code: '08015022', city: 'Badalona', name: 'Guàrdia Urbana'
Location.create code: '08015021', city: 'Badalona', name: 'Mont-roig - Ausiàs March'
Location.create code: '08252002', city: 'Barberà del Vallès', name: 'Ajuntament'
Location.create code: '08252006', city: 'Barberà del Vallès', name: 'Moragues - Montserrat'
Location.create code: '08054001', city: 'Castellbisbal', name: 'CEIP Mare de Déu de Montserrat'
Location.create code: '08054003', city: 'Castellbisbal', name: 'Mirador'
Location.create code: '08073001', city: 'Cornellà de Llobregat', name: 'Allende - Bonveí'
Location.create code: '08077002', city: 'Esplugues de Llobregat', name: 'CEIP Isidre Martí'
Location.create code: '08089003', city: 'Gavà', name: 'Centre'
Location.create code: '08089005', city: 'Gavà', name: 'Parc del Mil·leni'
Location.create code: '08096011', city: 'Granollers', name: 'Joan Vinyoli'
Location.create code: '08096014', city: 'Granollers', name: 'Francesc Macià'
Location.create code: '08101001', city: 'Hospitalet de Llobregat', name: 'Avinguda del Torrent Gornal'
Location.create code: '08114006', city: 'Martorell', name: 'Canyameres - Claret'
Location.create code: '08121009', city: 'Mataró', name: 'El Cros'
Location.create code: '08121014', city: 'Mataró', name: 'Laboratori d\'aigües'
Location.create code: '08121012', city: 'Mataró', name: 'Pablo Iglesias'
Location.create code: '08121013', city: 'Mataró', name: 'Passeig dels Molins'
Location.create code: '08123001', city: 'Molins de Rei', name: 'Ajuntament'
Location.create code: '08124009', city: 'Mollet del Vallès', name: 'Pista d\'atletisme'
Location.create code: '08187012', city: 'Sabadell', name: 'Gran Via'
Location.create code: '08187014', city: 'Sabadell', name: 'IES Escola Industrial'
Location.create code: '08194008', city: 'Sant Adrià de Besòs', name: 'Olímpic'
Location.create code: '08205002', city: 'Sant Cugat del Vallès', name: 'Parc de Sant Francesc'
Location.create code: '08211004', city: 'Sant Feliu de Llobregat', name: 'CEIP Martí i Pol'
Location.create code: '08211003', city: 'Sant Feliu de Llobregat', name: 'Eugeni d\'Ors'
Location.create code: '08221004', city: 'Sant Just Desvern', name: 'CEIP Montseny'
Location.create code: '08245013', city: 'Santa Coloma de Gramenet', name: 'Ajuntament'
Location.create code: '08245012', city: 'Santa Coloma de Gramenet', name: 'Balldovina'
Location.create code: '08270005', city: 'Sitges', name: 'Vallcarca Centre'
Location.create code: '08270004', city: 'Sitges', name: 'Vallcarca Dipòsit aigües'
Location.create code: '08270006', city: 'Sitges', name: 'Vallcarca Oficines'
Location.create code: '43148003', city: 'Tarragona', name: 'Bonavista'
Location.create code: '43148026', city: 'Tarragona', name: 'DARP'
Location.create code: '43148028', city: 'Tarragona', name: 'Parc de la Ciutat'
Location.create code: '43148001', city: 'Tarragona', name: 'Sant Salvador'
Location.create code: '43148022', city: 'Tarragona', name: 'Universitat Laboral'
Location.create code: '43148029', city: 'Tarragona', name: 'Port moll d\'inflamables'
Location.create code: '08279001', city: 'Terrassa', name: 'Mina pública d\'aigües'
Location.create code: '08279011', city: 'Terrassa', name: 'Pare Alegre'
Location.create code: '08282001', city: 'Tiana', name: 'Ajuntament'
Location.create code: '08298009', city: 'Vic', name: 'Centre cívic Santa Anna'
Location.create code: '08298008', city: 'Vic', name: 'Estadi'
Location.create code: '08301004', city: 'Viladecans', name: 'Atrium'
Location.create code: '17079003', city: 'Girona', name: 'Escola de Música'
Location.create code: '17079002', city: 'Girona', name: 'mercat del Lleó'
Location.create code: '17079001', city: 'Girona', name: 'parc de la Devesa'